---
name: Deploy

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  release:
    types:
      - published

permissions:
  actions: read
  contents: read
  packages: write
  security-events: write

jobs:
  ci:
    uses: erik73/workflows/.github/workflows/base-ci.yaml@6fd809e6e18800706d6efae8e8fa2995872adc42 # v1.1.1

  deploy:
    needs: ci
    uses: erik73/workflows/.github/workflows/base-deploy.yaml@6fd809e6e18800706d6efae8e8fa2995872adc42 # v1.1.1
