---
name: Deploy

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  release:
    types:
      - published

permissions:
  actions: read
  contents: read
  packages: write
  security-events: write

jobs:
  ci:
    uses: erik73/workflows/.github/workflows/base-ci.yaml@0d708a724ff0548b48e5aee5252cb33af09cc6db # v1.0.10

  deploy:
    needs: ci
    uses: erik73/workflows/.github/workflows/base-deploy.yaml@0d708a724ff0548b48e5aee5252cb33af09cc6db # v1.0.10
