---
name: Release Drafter

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  workflows:
    uses: erik73/workflows/.github/workflows/release-drafter.yaml@b825c628ef43b63d29c5884084db701d973a1879 # v2.0.3
